/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.Locale;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keith
 */
public class DashBoardPageAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    private Color defaultColor, clickedColor;
    private int empcount = 0;
    private LocalTime currentTime;
    String formattedTime;
    String formattedDate;
    String dayOfWeek;
    
    public DashBoardPageAdmin(String fname,String lname,String id,String birthday,String phone,
            String SSS,String philhealth,String TIN,String Pagibig,String pos,String salary,
            String grossrate, String hourlyrate,String status) {
        initComponents();
        resetData();
        displayTime();
        
        emp_countlbl.setText(String.valueOf(empcount));
        clickedColor = new Color(0,153,153);
        defaultColor = new Color(1,30,30);
        Dashboard_Panel.setBackground(clickedColor);
        Welcome_label.setText("Welcome back, "+fname+"!");
        Name_label.setText(fname+" "+lname);
        Status_label1.setText("Status: "+status);
        Emp_number_label.setText("Employee # "+id);
        bday_label2.setText("Birthdate: "+birthday);
        phoneNum_label1.setText("Phone: "+phone);
        SSS_label.setText("SSS: "+SSS);
        Philhealth_label.setText("Philhealth: "+philhealth);
        TIN_label.setText("TIN: "+TIN);
        Pagibig_label.setText("Pagibig: "+Pagibig);
        Pos_label.setText("Position: "+pos);
        Salary_label.setText("Basic Salary: "+salary);
        Hourly_rate_label.setText("Hourly Rate: "+hourlyrate);
        Grossrate_label.setText("Gross semi monthly rate: "+grossrate);
        
        
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Dashboard_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Profile_Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        EmployeeMang_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Payroll_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Leave_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Leave_panel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Dashboard_Tab = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        emp_countlbl = new javax.swing.JLabel();
        Welcome_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Profile_tab = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Name_label = new javax.swing.JLabel();
        Grossrate_label = new javax.swing.JLabel();
        Emp_number_label = new javax.swing.JLabel();
        Status_label1 = new javax.swing.JLabel();
        Pos_label = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        phoneNum_label1 = new javax.swing.JLabel();
        SSS_label = new javax.swing.JLabel();
        Philhealth_label = new javax.swing.JLabel();
        Pagibig_label = new javax.swing.JLabel();
        bday_label2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        TIN_label = new javax.swing.JLabel();
        Salary_label = new javax.swing.JLabel();
        Hourly_rate_label = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        Empmanage_tab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee_Table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        firstname_txtfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lastname_txtfield = new javax.swing.JTextField();
        addresstxtfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        birthdate_txtfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        position_txtfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        delete_btn1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        Payroll_tab = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        Leave_tab = new javax.swing.JPanel();
        Name_label1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Name_label2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(764, 450));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(1, 30, 30));
        jPanel2.setLayout(null);

        Dashboard_Panel.setBackground(new java.awt.Color(1, 30, 30));
        Dashboard_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Dashboard_PanelMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home (2) (1).png"))); // NOI18N
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout Dashboard_PanelLayout = new javax.swing.GroupLayout(Dashboard_Panel);
        Dashboard_Panel.setLayout(Dashboard_PanelLayout);
        Dashboard_PanelLayout.setHorizontalGroup(
            Dashboard_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dashboard_PanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        Dashboard_PanelLayout.setVerticalGroup(
            Dashboard_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(Dashboard_Panel);
        Dashboard_Panel.setBounds(0, 110, 202, 40);

        Profile_Panel.setBackground(new java.awt.Color(1, 30, 30));
        Profile_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Profile_PanelMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (2) (1).png"))); // NOI18N
        jLabel3.setText("Profile");

        javax.swing.GroupLayout Profile_PanelLayout = new javax.swing.GroupLayout(Profile_Panel);
        Profile_Panel.setLayout(Profile_PanelLayout);
        Profile_PanelLayout.setHorizontalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Profile_PanelLayout.setVerticalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(Profile_Panel);
        Profile_Panel.setBounds(0, 162, 202, 40);

        EmployeeMang_panel.setBackground(new java.awt.Color(1, 30, 30));
        EmployeeMang_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeMang_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeMang_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmployeeMang_panelMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employee (1).png"))); // NOI18N
        jLabel4.setText("Manage Employees");

        javax.swing.GroupLayout EmployeeMang_panelLayout = new javax.swing.GroupLayout(EmployeeMang_panel);
        EmployeeMang_panel.setLayout(EmployeeMang_panelLayout);
        EmployeeMang_panelLayout.setHorizontalGroup(
            EmployeeMang_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeMang_panelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        EmployeeMang_panelLayout.setVerticalGroup(
            EmployeeMang_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(EmployeeMang_panel);
        EmployeeMang_panel.setBounds(0, 214, 202, 40);

        Payroll_panel.setBackground(new java.awt.Color(1, 30, 30));
        Payroll_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Payroll_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Payroll_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Payroll_panelMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salary (1).png"))); // NOI18N
        jLabel5.setText("Payroll");

        javax.swing.GroupLayout Payroll_panelLayout = new javax.swing.GroupLayout(Payroll_panel);
        Payroll_panel.setLayout(Payroll_panelLayout);
        Payroll_panelLayout.setHorizontalGroup(
            Payroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Payroll_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        Payroll_panelLayout.setVerticalGroup(
            Payroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Payroll_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Payroll_panel);
        Payroll_panel.setBounds(0, 266, 202, 40);

        Leave_panel.setBackground(new java.awt.Color(1, 30, 30));
        Leave_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Leave_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Leave_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Leave_panelMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/turn-off (1).png"))); // NOI18N
        jLabel6.setText("Log out");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout Leave_panelLayout = new javax.swing.GroupLayout(Leave_panel);
        Leave_panel.setLayout(Leave_panelLayout);
        Leave_panelLayout.setHorizontalGroup(
            Leave_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave_panelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        Leave_panelLayout.setVerticalGroup(
            Leave_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Leave_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Leave_panel);
        Leave_panel.setBounds(0, 410, 202, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MotorPH");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 10, 77, 30);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/motorcycle (1).png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(70, 50, 60, 40);

        Leave_panel1.setBackground(new java.awt.Color(1, 30, 30));
        Leave_panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Leave_panel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Leave_panel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Leave_panel1MousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit (1).png"))); // NOI18N
        jLabel15.setText("Leave Request");

        javax.swing.GroupLayout Leave_panel1Layout = new javax.swing.GroupLayout(Leave_panel1);
        Leave_panel1.setLayout(Leave_panel1Layout);
        Leave_panel1Layout.setHorizontalGroup(
            Leave_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave_panel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        Leave_panel1Layout.setVerticalGroup(
            Leave_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Leave_panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Leave_panel1);
        Leave_panel1.setBounds(0, 318, 202, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 470);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(200, 0, 590, 50);

        Dashboard_Tab.setBackground(new java.awt.Color(245, 245, 245));
        Dashboard_Tab.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(1, 30, 30));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.setLayout(null);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employees (1) (1).png"))); // NOI18N
        jPanel4.add(jLabel23);
        jLabel23.setBounds(19, 30, 70, 70);

        jLabel24.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Total Employees");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(95, 83, 193, 34);

        emp_countlbl.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        emp_countlbl.setForeground(new java.awt.Color(255, 255, 255));
        emp_countlbl.setText("25");
        jPanel4.add(emp_countlbl);
        emp_countlbl.setBounds(319, 11, 28, 34);

        Dashboard_Tab.add(jPanel4);
        jPanel4.setBounds(33, 143, 358, 154);

        Welcome_label.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Welcome_label.setText("  Welcome back, User");
        Dashboard_Tab.add(Welcome_label);
        Welcome_label.setBounds(33, 82, 392, 27);

        jLabel7.setText("Welcome to MotorPh Employee Application!");
        Dashboard_Tab.add(jLabel7);
        jLabel7.setBounds(33, 115, 254, 16);

        jPanel8.setBackground(new java.awt.Color(153, 204, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        Dashboard_Tab.add(jPanel8);
        jPanel8.setBounds(397, 143, 170, 72);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Dashboard_Tab.add(jPanel9);
        jPanel9.setBounds(397, 221, 170, 76);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jLabel25.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel25.setText("Time");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("jLabel26");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(33, 33, 33))
        );

        Dashboard_Tab.add(jPanel10);
        jPanel10.setBounds(33, 309, 240, 128);

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Dashboard_Tab.add(jPanel11);
        jPanel11.setBounds(285, 309, 282, 128);

        jTabbedPane1.addTab("tab1", Dashboard_Tab);

        Profile_tab.setBackground(new java.awt.Color(245, 245, 245));
        Profile_tab.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (4) (2).png"))); // NOI18N
        Profile_tab.add(jLabel14);
        jLabel14.setBounds(35, 78, 150, 150);

        Name_label.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Name_label.setText("Manuel Garcia III");
        Profile_tab.add(Name_label);
        Name_label.setBounds(210, 80, 360, 40);

        Grossrate_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        Grossrate_label.setText("Gross semi Monthly:");
        Profile_tab.add(Grossrate_label);
        Grossrate_label.setBounds(310, 370, 270, 20);

        Emp_number_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        Emp_number_label.setText("Employee # : ");
        Profile_tab.add(Emp_number_label);
        Emp_number_label.setBounds(210, 120, 350, 20);

        Status_label1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        Status_label1.setText("Status:");
        Profile_tab.add(Status_label1);
        Status_label1.setBounds(210, 150, 350, 20);

        Pos_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        Pos_label.setText("Position:");
        Profile_tab.add(Pos_label);
        Pos_label.setBounds(210, 210, 360, 20);

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Profile_tab.add(jPanel6);
        jPanel6.setBounds(20, 240, 560, 20);

        phoneNum_label1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        phoneNum_label1.setText("Phone:");
        Profile_tab.add(phoneNum_label1);
        phoneNum_label1.setBounds(20, 310, 260, 20);

        SSS_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        SSS_label.setText("SSS:");
        Profile_tab.add(SSS_label);
        SSS_label.setBounds(20, 340, 260, 20);

        Philhealth_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        Philhealth_label.setText("Philhealth");
        Profile_tab.add(Philhealth_label);
        Philhealth_label.setBounds(20, 370, 260, 20);

        Pagibig_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        Pagibig_label.setText("Pagibig:");
        Profile_tab.add(Pagibig_label);
        Pagibig_label.setBounds(20, 400, 260, 20);

        bday_label2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        bday_label2.setText("Birthdate:");
        Profile_tab.add(bday_label2);
        bday_label2.setBounds(210, 180, 370, 20);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        Profile_tab.add(jPanel5);
        jPanel5.setBounds(290, 270, 10, 190);

        TIN_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        TIN_label.setText("TIN:");
        Profile_tab.add(TIN_label);
        TIN_label.setBounds(20, 430, 260, 20);

        Salary_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        Salary_label.setText("Basic Salary:");
        Profile_tab.add(Salary_label);
        Salary_label.setBounds(310, 310, 270, 20);

        Hourly_rate_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        Hourly_rate_label.setText("Hourly Rate:");
        Profile_tab.add(Hourly_rate_label);
        Hourly_rate_label.setBounds(310, 340, 270, 20);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel16.setText("Compensation Details");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        Profile_tab.add(jPanel7);
        jPanel7.setBounds(310, 270, 270, 30);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel17.setText("Numbers");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Profile_tab.add(jPanel12);
        jPanel12.setBounds(20, 270, 260, 30);

        jTabbedPane1.addTab("tab2", Profile_tab);

        Empmanage_tab.setBackground(new java.awt.Color(245, 245, 245));
        Empmanage_tab.setLayout(null);

        employee_Table.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        employee_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee #", "Last Name", "First Name", "Address", "Birthdate", "Position"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employee_Table.setFocusable(false);
        employee_Table.setGridColor(new java.awt.Color(0, 0, 0));
        employee_Table.setInheritsPopupMenu(true);
        employee_Table.setShowGrid(true);
        employee_Table.getTableHeader().setReorderingAllowed(false);
        employee_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                employee_TableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(employee_Table);

        Empmanage_tab.add(jScrollPane1);
        jScrollPane1.setBounds(6, 267, 584, 200);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("First Name");
        Empmanage_tab.add(jLabel8);
        jLabel8.setBounds(16, 77, 76, 29);
        Empmanage_tab.add(firstname_txtfield);
        firstname_txtfield.setBounds(98, 78, 190, 29);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Last Name");
        Empmanage_tab.add(jLabel9);
        jLabel9.setBounds(16, 113, 76, 29);
        Empmanage_tab.add(lastname_txtfield);
        lastname_txtfield.setBounds(98, 114, 190, 29);
        Empmanage_tab.add(addresstxtfield);
        addresstxtfield.setBounds(98, 150, 190, 29);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Address");
        Empmanage_tab.add(jLabel10);
        jLabel10.setBounds(16, 149, 76, 29);
        Empmanage_tab.add(birthdate_txtfield);
        birthdate_txtfield.setBounds(394, 78, 172, 29);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Birthdate");
        Empmanage_tab.add(jLabel11);
        jLabel11.setBounds(312, 77, 76, 29);
        Empmanage_tab.add(position_txtfield);
        position_txtfield.setBounds(394, 114, 172, 29);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Position");
        Empmanage_tab.add(jLabel12);
        jLabel12.setBounds(312, 113, 76, 29);

        add_btn.setBackground(new java.awt.Color(0, 153, 153));
        add_btn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        add_btn.setForeground(new java.awt.Color(255, 255, 255));
        add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add (1).png"))); // NOI18N
        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        Empmanage_tab.add(add_btn);
        add_btn.setBounds(240, 220, 78, 35);

        edit_btn.setBackground(new java.awt.Color(0, 153, 153));
        edit_btn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        edit_btn.setForeground(new java.awt.Color(255, 255, 255));
        edit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit (1).png"))); // NOI18N
        edit_btn.setText("Edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });
        Empmanage_tab.add(edit_btn);
        edit_btn.setBounds(320, 220, 78, 35);

        delete_btn.setBackground(new java.awt.Color(0, 153, 153));
        delete_btn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete (1).png"))); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        Empmanage_tab.add(delete_btn);
        delete_btn.setBounds(400, 220, 89, 35);

        delete_btn1.setBackground(new java.awt.Color(0, 153, 153));
        delete_btn1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        delete_btn1.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rubber (1).png"))); // NOI18N
        delete_btn1.setText("Clear");
        delete_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btn1ActionPerformed(evt);
            }
        });
        Empmanage_tab.add(delete_btn1);
        delete_btn1.setBounds(490, 220, 83, 35);

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Empmanage_tab.add(jPanel13);
        jPanel13.setBounds(20, 190, 560, 10);

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));

        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel22.setText("Employee List");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Empmanage_tab.add(jPanel17);
        jPanel17.setBounds(20, 220, 210, 40);

        jTabbedPane1.addTab("tab3", Empmanage_tab);

        Payroll_tab.setBackground(new java.awt.Color(245, 245, 245));

        jButton4.setText("Tab4");

        javax.swing.GroupLayout Payroll_tabLayout = new javax.swing.GroupLayout(Payroll_tab);
        Payroll_tab.setLayout(Payroll_tabLayout);
        Payroll_tabLayout.setHorizontalGroup(
            Payroll_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Payroll_tabLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jButton4)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        Payroll_tabLayout.setVerticalGroup(
            Payroll_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Payroll_tabLayout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(150, 150, 150))
        );

        jTabbedPane1.addTab("tab4", Payroll_tab);

        Leave_tab.setBackground(new java.awt.Color(245, 245, 245));
        Leave_tab.setLayout(null);

        Name_label1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Name_label1.setText("Your requests");
        Leave_tab.add(Name_label1);
        Name_label1.setBounds(330, 70, 250, 40);

        jPanel14.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Leave_tab.add(jPanel14);
        jPanel14.setBounds(330, 110, 250, 10);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacation Leave", "Sick Leave", "Maternity Leave", "Personal Leave", "Family or Medical Leave" }));
        Leave_tab.add(jComboBox1);
        jComboBox1.setBounds(30, 160, 240, 40);

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel18.setText("Start date of Leave*");
        Leave_tab.add(jLabel18);
        jLabel18.setBounds(30, 220, 160, 20);
        Leave_tab.add(jTextField1);
        jTextField1.setBounds(30, 240, 240, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel19.setText("Leave type*");
        Leave_tab.add(jLabel19);
        jLabel19.setBounds(30, 140, 80, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel20.setText("Reason of leave*");
        Leave_tab.add(jLabel20);
        jLabel20.setBounds(30, 360, 130, 20);
        Leave_tab.add(jTextField2);
        jTextField2.setBounds(30, 310, 240, 30);
        Leave_tab.add(jTextField3);
        jTextField3.setBounds(30, 380, 240, 80);

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel21.setText("End date of Leave*");
        Leave_tab.add(jLabel21);
        jLabel21.setBounds(30, 290, 130, 20);

        Name_label2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Name_label2.setText("Request new leave");
        Leave_tab.add(Name_label2);
        Name_label2.setBounds(20, 70, 250, 40);

        jPanel15.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Leave_tab.add(jPanel15);
        jPanel15.setBounds(20, 110, 250, 10);

        jPanel16.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        Leave_tab.add(jPanel16);
        jPanel16.setBounds(290, 70, 10, 390);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Request Leave");
        Leave_tab.add(jButton1);
        jButton1.setBounds(440, 420, 120, 30);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        Leave_tab.add(jScrollPane2);
        jScrollPane2.setBounds(330, 140, 240, 146);

        jTabbedPane1.addTab("tab5", Leave_tab);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(194, -40, 590, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void displayTime(){
        currentTime = LocalTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm a");
        formattedTime = currentTime.format(formatter);
        jLabel25.setText(formattedTime);
        
        LocalDate currentDate = LocalDate.now();
        
        // Format the date (optional)
        DateTimeFormatter formatters = DateTimeFormatter.ofPattern("MMM dd, yyyy");
         formattedDate = currentDate.format(formatters);
        
        // Get the day of the week
        dayOfWeek = currentDate.getDayOfWeek().getDisplayName(TextStyle.FULL, Locale.ENGLISH);
        jLabel26.setText(formattedDate);
    }
    
    private void resetData(){
        String query = null;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection(SUrl,SUser,SPass); 
                Statement st = con.createStatement();
                
                query = "SELECT * FROM users";
                ResultSet rs = st.executeQuery(query);
                
                while(rs.next()){
                    String id = String.valueOf(rs.getInt("id"));
                    String Lastname = rs.getString("Last Name");
                    String Firstname = rs.getString("First Name");
                    String Address = rs.getString("Address");
                    String Birthdate = rs.getString("Birthdate");
                    String Position = rs.getString("Position");
                    
                    String tbdata [] = {id,Lastname,Firstname,Address,Birthdate,Position};
                    DefaultTableModel tablemodel = (DefaultTableModel)employee_Table.getModel();
                    
                    tablemodel.addRow(tbdata);
                    empcount++;
                    
                }
            
            
            
            
            
        }catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }
    private void EmployeeMang_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMang_panelMousePressed
        Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(defaultColor);
        EmployeeMang_panel.setBackground(clickedColor);
        Payroll_panel.setBackground(defaultColor);
        Leave_panel.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_EmployeeMang_panelMousePressed

    private void Payroll_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Payroll_panelMousePressed
        Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(defaultColor);
        EmployeeMang_panel.setBackground(defaultColor);
        Payroll_panel.setBackground(clickedColor);
        Leave_panel1.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_Payroll_panelMousePressed

    private void Leave_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leave_panelMousePressed
         
    }//GEN-LAST:event_Leave_panelMousePressed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
        String query = null;
        
        int selected = employee_Table.getSelectedRow();
         if (selected<0){
                showMessageDialog(null,"Please select an employee to remove","Error",JOptionPane.ERROR_MESSAGE);
            }
         else{
        int response = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete?","Confirm",JOptionPane.YES_NO_OPTION);
        int id = Integer.parseInt(employee_Table.getValueAt(employee_Table.getSelectedRow(),0).toString());

             if(response == JOptionPane.YES_OPTION){
        try{    
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = con.createStatement();
            query = ("DELETE FROM users where id="+id);
            st.execute(query);
            
            DefaultTableModel tablemodel = (DefaultTableModel)employee_Table.getModel();
            tablemodel.setRowCount(0);   
            resetData();
            
            firstname_txtfield.setText("");
            lastname_txtfield.setText("");
            addresstxtfield.setText("");
            birthdate_txtfield.setText("");
            position_txtfield.setText("");
            
            showMessageDialog(null,"Deleted Successfully","Message",JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch(Exception e){
            System.out.println("Error: "+ e.getMessage());
        }
             }else if(response == JOptionPane.NO_OPTION){
            firstname_txtfield.setText("");
            lastname_txtfield.setText("");
            addresstxtfield.setText("");
            birthdate_txtfield.setText("");
            position_txtfield.setText(""); 
             }
             
        
         }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        String query, lastname,firstname,address,birthdate,Position;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = con.createStatement();
            if(firstname_txtfield.getText().isBlank()||lastname_txtfield.getText().isBlank()
                    ||addresstxtfield.getText().isBlank()||birthdate_txtfield.getText().isBlank()
                    ||position_txtfield.getText().isBlank()){
                showMessageDialog(null,"Please fillup all information","Invalid",JOptionPane.ERROR_MESSAGE);
            }
            else{
            firstname = firstname_txtfield.getText();
            lastname= lastname_txtfield.getText();
            address= addresstxtfield.getText();
            birthdate= birthdate_txtfield.getText();
            Position = position_txtfield.getText();
                                                                     
            query = "INSERT INTO users(`Last Name`, `First Name`, Address, Birthdate, Position) " + "VALUES('"+ lastname +"', '"+ firstname +"', '"+ address +"', '"+ birthdate +"', '"+ Position +"')";
                                    
            st.execute(query);
            
            DefaultTableModel tablemodel = (DefaultTableModel)employee_Table.getModel();
            tablemodel.setRowCount(0);            
          
            resetData();
            firstname_txtfield.setText("");
            lastname_txtfield.setText("");
            addresstxtfield.setText("");
            birthdate_txtfield.setText("");
            position_txtfield.setText("");
            
            showMessageDialog(null,"Addedd Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        String query, lastname,firstname,address,birthdate,Position;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
        int selected = employee_Table.getSelectedRow();
        if(selected<0){
            showMessageDialog(null,"Please select an employee to update","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        try{
            int confirm = JOptionPane.showConfirmDialog(null,"Are you sure you want to update?","Confirm",JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
            
            int id = Integer.parseInt(employee_Table.getValueAt(employee_Table.getSelectedRow(),0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = con.createStatement();
            
            firstname = firstname_txtfield.getText();
            lastname= lastname_txtfield.getText();
            address= addresstxtfield.getText();
            birthdate= birthdate_txtfield.getText();
            Position = position_txtfield.getText();
            
            query = ("UPDATE users set `First Name`='"+firstname+"',`Last Name`='"+lastname+"',Address = '"+address+"',Birthdate = '"+birthdate+"',Position ='"+Position+"' where id="+id);
            st.executeUpdate(query);
                         
            DefaultTableModel tablemodel = (DefaultTableModel)employee_Table.getModel();
            tablemodel.setRowCount(0);
            
            resetData();
            
            firstname_txtfield.setText("");
            lastname_txtfield.setText("");
            addresstxtfield.setText("");
            birthdate_txtfield.setText("");
            position_txtfield.setText("");
            showMessageDialog(null,"Update Successful!","Message",JOptionPane.INFORMATION_MESSAGE);
            
            }

            
            
        }catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
        }
    }//GEN-LAST:event_edit_btnActionPerformed

    private void delete_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btn1ActionPerformed
        firstname_txtfield.setText("");
            lastname_txtfield.setText("");
            addresstxtfield.setText("");
            birthdate_txtfield.setText("");
            position_txtfield.setText("");
            
    }//GEN-LAST:event_delete_btn1ActionPerformed

    private void EmployeeMang_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMang_panelMouseEntered
        
    }//GEN-LAST:event_EmployeeMang_panelMouseEntered

    private void EmployeeMang_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMang_panelMouseExited
      
    }//GEN-LAST:event_EmployeeMang_panelMouseExited

    private void Payroll_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Payroll_panelMouseEntered
    
    }//GEN-LAST:event_Payroll_panelMouseEntered

    private void Payroll_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Payroll_panelMouseExited
    
    }//GEN-LAST:event_Payroll_panelMouseExited

    private void Leave_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leave_panelMouseEntered
      
    }//GEN-LAST:event_Leave_panelMouseEntered

    private void Leave_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leave_panelMouseExited
      
    }//GEN-LAST:event_Leave_panelMouseExited

    private void Dashboard_PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard_PanelMousePressed
         Dashboard_Panel.setBackground(clickedColor);
        Profile_Panel.setBackground(defaultColor);
        EmployeeMang_panel.setBackground(defaultColor);
        Payroll_panel.setBackground(defaultColor);
        Leave_panel1.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Dashboard_PanelMousePressed

    private void Profile_PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_PanelMousePressed
        Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(clickedColor);
        EmployeeMang_panel.setBackground(defaultColor);
        Payroll_panel.setBackground(defaultColor);
        Leave_panel1.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_Profile_PanelMousePressed

    private void employee_TableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_TableMousePressed
        String query = null;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
 
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = con.createStatement();
            int id = Integer.parseInt(employee_Table.getValueAt(employee_Table.getSelectedRow(),0).toString());
            query = ("SELECT * from users where id="+id);
            ResultSet rs = st.executeQuery(query);
            
            
            while(rs.next()){
                firstname_txtfield.setText(rs.getString("First Name"));
                lastname_txtfield.setText(rs.getString("Last Name"));
                addresstxtfield.setText(rs.getString("Address"));
                birthdate_txtfield.setText(rs.getString("Birthdate"));
                position_txtfield.setText(rs.getString("Position"));
            }
            
        }catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_employee_TableMousePressed

    private void Leave_panel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leave_panel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Leave_panel1MouseEntered

    private void Leave_panel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leave_panel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Leave_panel1MouseExited

    private void Leave_panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leave_panel1MousePressed
        Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(defaultColor);
        EmployeeMang_panel.setBackground(defaultColor);
        Payroll_panel.setBackground(defaultColor);
        Leave_panel1.setBackground(clickedColor);
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_Leave_panel1MousePressed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jLabel6.setForeground(clickedColor);
        jLabel6.setFont(new Font("Segoe UI Emoji",Font.BOLD,15));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(new Color(255,255,255));
        jLabel6.setFont(new Font("Segoe UI Emoji",Font.BOLD,14));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        int response = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Confirm",JOptionPane.YES_NO_OPTION);
        if(response == JOptionPane.YES_OPTION){
            this.dispose();
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_jLabel6MousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashBoardPageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashBoardPageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashBoardPageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashBoardPageAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashBoardPageAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard_Panel;
    private javax.swing.JPanel Dashboard_Tab;
    private javax.swing.JLabel Emp_number_label;
    private javax.swing.JPanel EmployeeMang_panel;
    private javax.swing.JPanel Empmanage_tab;
    private javax.swing.JLabel Grossrate_label;
    private javax.swing.JLabel Hourly_rate_label;
    private javax.swing.JPanel Leave_panel;
    private javax.swing.JPanel Leave_panel1;
    private javax.swing.JPanel Leave_tab;
    private javax.swing.JLabel Name_label;
    private javax.swing.JLabel Name_label1;
    private javax.swing.JLabel Name_label2;
    private javax.swing.JLabel Pagibig_label;
    private javax.swing.JPanel Payroll_panel;
    private javax.swing.JPanel Payroll_tab;
    private javax.swing.JLabel Philhealth_label;
    private javax.swing.JLabel Pos_label;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JPanel Profile_tab;
    private javax.swing.JLabel SSS_label;
    private javax.swing.JLabel Salary_label;
    private javax.swing.JLabel Status_label1;
    private javax.swing.JLabel TIN_label;
    private javax.swing.JLabel Welcome_label;
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField addresstxtfield;
    private javax.swing.JLabel bday_label2;
    private javax.swing.JTextField birthdate_txtfield;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton delete_btn1;
    private javax.swing.JButton edit_btn;
    private javax.swing.JLabel emp_countlbl;
    private javax.swing.JTable employee_Table;
    private javax.swing.JTextField firstname_txtfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField lastname_txtfield;
    private javax.swing.JLabel phoneNum_label1;
    private javax.swing.JTextField position_txtfield;
    // End of variables declaration//GEN-END:variables
}
