/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keith
 */
public class DashBoardPageEmployee extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    private Color defaultColor, clickedColor;
    private int empcount = 0;
    
    public DashBoardPageEmployee(String fname,String lname,String id,String birthday,String phone,
            String SSS,String philhealth,String TIN,String Pagibig,String pos,String salary,
            String grossrate, String hourlyrate,String status) {
        initComponents();
        countEmployees();
        emp_countlbl.setText(String.valueOf(empcount));
        clickedColor = new Color(0,153,153);
        defaultColor = new Color(1,30,30);
        Dashboard_Panel.setBackground(clickedColor);
        Welcome_label.setText("Welcome back, "+fname+"!");
        fullname.setText(fname+" "+lname);
        status_label.setText("Status: "+status);
        id_label.setText("Employee # "+id);
        bdaylabel.setText("Birthdate: "+birthday);
        phonelabel.setText("Phone: "+phone);
        ssslabel.setText("SSS: "+SSS);
        philhealthlabbel.setText("Philhealth: "+philhealth);
        tinlabel.setText("TIN: "+TIN);
        pagibiglabel.setText("Pagibig: "+Pagibig);
        positionlabel.setText("Position: "+pos);
        basicsalarylabel.setText("Basic Salary: "+salary);
        hourlyratelabel.setText("Hourly Rate: "+hourlyrate);
        grossratelabel.setText("Gross semi monthly rate: "+grossrate);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Dashboard_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Profile_Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Payroll_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Leave_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Dashboard_Tab = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelemp = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        emp_countlbl = new javax.swing.JLabel();
        Welcome_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Profile_tab = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        status_label = new javax.swing.JLabel();
        bdaylabel = new javax.swing.JLabel();
        positionlabel = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        phonelabel = new javax.swing.JLabel();
        ssslabel = new javax.swing.JLabel();
        philhealthlabbel = new javax.swing.JLabel();
        pagibiglabel = new javax.swing.JLabel();
        tinlabel = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        grossratelabel = new javax.swing.JLabel();
        hourlyratelabel = new javax.swing.JLabel();
        basicsalarylabel = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Payroll_tab = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        Leave_tab = new javax.swing.JPanel();
        Name_label1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        Name_label2 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(764, 450));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(1, 30, 30));
        jPanel2.setLayout(null);

        Dashboard_Panel.setBackground(new java.awt.Color(1, 30, 30));
        Dashboard_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Dashboard_PanelMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home (2) (1).png"))); // NOI18N
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout Dashboard_PanelLayout = new javax.swing.GroupLayout(Dashboard_Panel);
        Dashboard_Panel.setLayout(Dashboard_PanelLayout);
        Dashboard_PanelLayout.setHorizontalGroup(
            Dashboard_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dashboard_PanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        Dashboard_PanelLayout.setVerticalGroup(
            Dashboard_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(Dashboard_Panel);
        Dashboard_Panel.setBounds(0, 110, 202, 40);

        Profile_Panel.setBackground(new java.awt.Color(1, 30, 30));
        Profile_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Profile_PanelMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (2) (1).png"))); // NOI18N
        jLabel3.setText("Profile");

        javax.swing.GroupLayout Profile_PanelLayout = new javax.swing.GroupLayout(Profile_Panel);
        Profile_Panel.setLayout(Profile_PanelLayout);
        Profile_PanelLayout.setHorizontalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        Profile_PanelLayout.setVerticalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(Profile_Panel);
        Profile_Panel.setBounds(0, 160, 202, 40);

        Payroll_panel.setBackground(new java.awt.Color(1, 30, 30));
        Payroll_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Payroll_panelMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salary (1).png"))); // NOI18N
        jLabel5.setText("Payroll");

        javax.swing.GroupLayout Payroll_panelLayout = new javax.swing.GroupLayout(Payroll_panel);
        Payroll_panel.setLayout(Payroll_panelLayout);
        Payroll_panelLayout.setHorizontalGroup(
            Payroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Payroll_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        Payroll_panelLayout.setVerticalGroup(
            Payroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Payroll_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Payroll_panel);
        Payroll_panel.setBounds(0, 210, 202, 40);

        Leave_panel.setBackground(new java.awt.Color(1, 30, 30));
        Leave_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Leave_panelMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit (1).png"))); // NOI18N
        jLabel6.setText("Leave Request");

        javax.swing.GroupLayout Leave_panelLayout = new javax.swing.GroupLayout(Leave_panel);
        Leave_panel.setLayout(Leave_panelLayout);
        Leave_panelLayout.setHorizontalGroup(
            Leave_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        Leave_panelLayout.setVerticalGroup(
            Leave_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Leave_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(Leave_panel);
        Leave_panel.setBounds(0, 260, 202, 40);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/motorcycle (1).png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 50, 60, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MotorPH");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(50, 10, 77, 30);

        jPanel8.setBackground(new java.awt.Color(1, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/turn-off (1).png"))); // NOI18N
        jLabel8.setText("Log out");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel8);
        jPanel8.setBounds(0, 410, 200, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 470);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(200, 0, 590, 50);

        Dashboard_Tab.setBackground(new java.awt.Color(245, 245, 245));
        Dashboard_Tab.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(1, 30, 30));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabelemp.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabelemp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelemp.setText("Total Employees");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\keith\\OneDrive\\Desktop\\Icons\\employees (1) (1).png")); // NOI18N

        emp_countlbl.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        emp_countlbl.setForeground(new java.awt.Color(255, 255, 255));
        emp_countlbl.setText("25");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelemp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emp_countlbl)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(emp_countlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabelemp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        Dashboard_Tab.add(jPanel4);
        jPanel4.setBounds(30, 140, 360, 154);

        Welcome_label.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Welcome_label.setText("Welcome back, User");
        Dashboard_Tab.add(Welcome_label);
        Welcome_label.setBounds(31, 80, 380, 27);

        jLabel7.setText("Welcome to MotorPh Employee Application!");
        Dashboard_Tab.add(jLabel7);
        jLabel7.setBounds(30, 110, 254, 16);

        jPanel9.setBackground(new java.awt.Color(153, 204, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        Dashboard_Tab.add(jPanel9);
        jPanel9.setBounds(400, 140, 170, 72);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Dashboard_Tab.add(jPanel5);
        jPanel5.setBounds(400, 220, 170, 70);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        Dashboard_Tab.add(jPanel6);
        jPanel6.setBounds(30, 310, 220, 130);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        Dashboard_Tab.add(jPanel7);
        jPanel7.setBounds(260, 310, 310, 130);

        jTabbedPane1.addTab("tab1", Dashboard_Tab);

        Profile_tab.setBackground(new java.awt.Color(245, 245, 245));
        Profile_tab.setLayout(null);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (4) (2).png"))); // NOI18N
        Profile_tab.add(jLabel14);
        jLabel14.setBounds(35, 78, 150, 150);

        fullname.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        fullname.setText("Manuel Garcia III");
        Profile_tab.add(fullname);
        fullname.setBounds(210, 80, 360, 40);

        id_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        id_label.setText("Employee # : ");
        Profile_tab.add(id_label);
        id_label.setBounds(210, 120, 350, 20);

        status_label.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        status_label.setText("Status:");
        Profile_tab.add(status_label);
        status_label.setBounds(210, 150, 350, 20);

        bdaylabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        bdaylabel.setText("Birthdate:");
        Profile_tab.add(bdaylabel);
        bdaylabel.setBounds(210, 180, 370, 20);

        positionlabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        positionlabel.setText("Position:");
        Profile_tab.add(positionlabel);
        positionlabel.setBounds(210, 210, 360, 20);

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Profile_tab.add(jPanel13);
        jPanel13.setBounds(20, 240, 560, 20);

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));

        jLabel17.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel17.setText("Numbers");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Profile_tab.add(jPanel14);
        jPanel14.setBounds(20, 270, 260, 30);

        phonelabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        phonelabel.setText("Phone:");
        Profile_tab.add(phonelabel);
        phonelabel.setBounds(20, 310, 260, 20);

        ssslabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        ssslabel.setText("SSS:");
        Profile_tab.add(ssslabel);
        ssslabel.setBounds(20, 340, 260, 20);

        philhealthlabbel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        philhealthlabbel.setText("Philhealth");
        Profile_tab.add(philhealthlabbel);
        philhealthlabbel.setBounds(20, 370, 260, 20);

        pagibiglabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        pagibiglabel.setText("Pagibig:");
        Profile_tab.add(pagibiglabel);
        pagibiglabel.setBounds(20, 400, 260, 20);

        tinlabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        tinlabel.setText("TIN:");
        Profile_tab.add(tinlabel);
        tinlabel.setBounds(20, 430, 260, 20);

        jPanel15.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        Profile_tab.add(jPanel15);
        jPanel15.setBounds(290, 270, 10, 190);

        grossratelabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        grossratelabel.setText("Gross semi Monthly:");
        Profile_tab.add(grossratelabel);
        grossratelabel.setBounds(310, 370, 270, 20);

        hourlyratelabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        hourlyratelabel.setText("Hourly Rate:");
        Profile_tab.add(hourlyratelabel);
        hourlyratelabel.setBounds(310, 340, 270, 20);

        basicsalarylabel.setFont(new java.awt.Font("Segoe UI Emoji", 0, 15)); // NOI18N
        basicsalarylabel.setText("Basic Salary:");
        Profile_tab.add(basicsalarylabel);
        basicsalarylabel.setBounds(310, 310, 270, 20);

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel16.setText("Compensation Details");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
        );

        Profile_tab.add(jPanel16);
        jPanel16.setBounds(310, 270, 270, 30);

        jTabbedPane1.addTab("tab2", Profile_tab);

        Payroll_tab.setBackground(new java.awt.Color(245, 245, 245));

        jButton4.setText("Tab4");

        javax.swing.GroupLayout Payroll_tabLayout = new javax.swing.GroupLayout(Payroll_tab);
        Payroll_tab.setLayout(Payroll_tabLayout);
        Payroll_tabLayout.setHorizontalGroup(
            Payroll_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Payroll_tabLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jButton4)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        Payroll_tabLayout.setVerticalGroup(
            Payroll_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Payroll_tabLayout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(150, 150, 150))
        );

        jTabbedPane1.addTab("tab4", Payroll_tab);

        Leave_tab.setBackground(new java.awt.Color(245, 245, 245));
        Leave_tab.setLayout(null);

        Name_label1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Name_label1.setText("Request new leave");
        Leave_tab.add(Name_label1);
        Name_label1.setBounds(20, 70, 360, 40);

        jPanel17.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Leave_tab.add(jPanel17);
        jPanel17.setBounds(20, 110, 250, 10);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Leave_tab.add(jComboBox1);
        jComboBox1.setBounds(30, 160, 240, 40);

        jLabel19.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel19.setText("Leave type*");
        Leave_tab.add(jLabel19);
        jLabel19.setBounds(30, 140, 80, 20);

        jLabel18.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel18.setText("Start date of Leave*");
        Leave_tab.add(jLabel18);
        jLabel18.setBounds(30, 220, 160, 20);
        Leave_tab.add(jTextField1);
        jTextField1.setBounds(30, 240, 240, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel21.setText("End date of Leave*");
        Leave_tab.add(jLabel21);
        jLabel21.setBounds(30, 290, 130, 20);
        Leave_tab.add(jTextField2);
        jTextField2.setBounds(30, 310, 240, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel20.setText("Reason of leave*");
        Leave_tab.add(jLabel20);
        jLabel20.setBounds(30, 360, 130, 20);
        Leave_tab.add(jTextField3);
        jTextField3.setBounds(30, 380, 240, 80);

        Name_label2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        Name_label2.setText("Your requests");
        Leave_tab.add(Name_label2);
        Name_label2.setBounds(330, 70, 250, 40);

        jPanel18.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        Leave_tab.add(jPanel18);
        jPanel18.setBounds(290, 70, 10, 390);

        jPanel19.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Leave_tab.add(jPanel19);
        jPanel19.setBounds(330, 110, 250, 10);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        Leave_tab.add(jScrollPane2);
        jScrollPane2.setBounds(330, 140, 240, 146);

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Request Leave");
        Leave_tab.add(jButton1);
        jButton1.setBounds(440, 420, 120, 30);

        jTabbedPane1.addTab("tab5", Leave_tab);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(194, -40, 590, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    private void countEmployees(){
        String query = null;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection(SUrl,SUser,SPass); 
                Statement st = con.createStatement();
                
                query = "SELECT * FROM users";
                ResultSet rs = st.executeQuery(query);
                
                while(rs.next()){
                  
                    empcount++;
                    
                }
            
            
            
            
            
        }catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }
 
    private void Payroll_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Payroll_panelMousePressed
        Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(defaultColor);
        
        Payroll_panel.setBackground(clickedColor);
        Leave_panel.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_Payroll_panelMousePressed

    private void Leave_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leave_panelMousePressed
         Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(defaultColor);
        
        Payroll_panel.setBackground(defaultColor);
        Leave_panel.setBackground(clickedColor);
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_Leave_panelMousePressed

    private void Dashboard_PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard_PanelMousePressed
         Dashboard_Panel.setBackground(clickedColor);
        Profile_Panel.setBackground(defaultColor);
        
        Payroll_panel.setBackground(defaultColor);
        Leave_panel.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Dashboard_PanelMousePressed

    private void Profile_PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_PanelMousePressed
        Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(clickedColor);
        
        Payroll_panel.setBackground(defaultColor);
        Leave_panel.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_Profile_PanelMousePressed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        jLabel8.setForeground(clickedColor);
        jLabel8.setFont(new Font("Segoe UI Emoji",Font.BOLD,15));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        jLabel8.setForeground(new Color(255,255,255));
        jLabel8.setFont(new Font("Segoe UI Emoji",Font.BOLD,15));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        int response = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?","Confirm",JOptionPane.YES_NO_OPTION);
        if(response == JOptionPane.YES_OPTION){
            this.dispose();
            new LoginPage().setVisible(true);
        }

    }//GEN-LAST:event_jLabel8MousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DashBoardPageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DashBoardPageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DashBoardPageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DashBoardPageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashBoardPageEmployee().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard_Panel;
    private javax.swing.JPanel Dashboard_Tab;
    private javax.swing.JPanel Leave_panel;
    private javax.swing.JPanel Leave_tab;
    private javax.swing.JLabel Name_label1;
    private javax.swing.JLabel Name_label2;
    private javax.swing.JPanel Payroll_panel;
    private javax.swing.JPanel Payroll_tab;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JPanel Profile_tab;
    private javax.swing.JLabel Welcome_label;
    private javax.swing.JLabel basicsalarylabel;
    private javax.swing.JLabel bdaylabel;
    private javax.swing.JLabel emp_countlbl;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel grossratelabel;
    private javax.swing.JLabel hourlyratelabel;
    private javax.swing.JLabel id_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelemp;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel pagibiglabel;
    private javax.swing.JLabel philhealthlabbel;
    private javax.swing.JLabel phonelabel;
    private javax.swing.JLabel positionlabel;
    private javax.swing.JLabel ssslabel;
    private javax.swing.JLabel status_label;
    private javax.swing.JLabel tinlabel;
    // End of variables declaration//GEN-END:variables
}
