/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keith
 */
public class DashBoardPage extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    Color defaultColor, clickedColor;
    private Boolean isClicked = false;
    public DashBoardPage() {
        initComponents();
        resetData();
        clickedColor = new Color(255,153,0);
        defaultColor = new Color(33,33,33);
        Dashboard_Panel.setBackground(clickedColor);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Dashboard_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Profile_Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        EmployeeMang_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Payroll_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Leave_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logout_bttn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Dashboard_Tab = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        list2 = new java.awt.List();
        Profile_tab = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Empmanage_tab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employee_Table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        firstname_txtfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lastname_txtfield = new javax.swing.JTextField();
        addresstxtfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        birthdate_txtfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        position_txtfield = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        delete_btn1 = new javax.swing.JButton();
        Payroll_tab = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        Leave_tab = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(764, 450));

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(23, 22, 22));

        Dashboard_Panel.setBackground(new java.awt.Color(33, 33, 33));
        Dashboard_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Dashboard_PanelMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home (2) (1).png"))); // NOI18N
        jLabel2.setText("Dashboard");

        javax.swing.GroupLayout Dashboard_PanelLayout = new javax.swing.GroupLayout(Dashboard_Panel);
        Dashboard_Panel.setLayout(Dashboard_PanelLayout);
        Dashboard_PanelLayout.setHorizontalGroup(
            Dashboard_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Dashboard_PanelLayout.setVerticalGroup(
            Dashboard_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dashboard_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Profile_Panel.setBackground(new java.awt.Color(33, 33, 33));
        Profile_Panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Profile_PanelMousePressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 153));
        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (2) (1).png"))); // NOI18N
        jLabel3.setText("Profile");

        javax.swing.GroupLayout Profile_PanelLayout = new javax.swing.GroupLayout(Profile_Panel);
        Profile_Panel.setLayout(Profile_PanelLayout);
        Profile_PanelLayout.setHorizontalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Profile_PanelLayout.setVerticalGroup(
            Profile_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        EmployeeMang_panel.setBackground(new java.awt.Color(33, 33, 33));
        EmployeeMang_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmployeeMang_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmployeeMang_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmployeeMang_panelMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/employee (1).png"))); // NOI18N
        jLabel4.setText("Employee Management");

        javax.swing.GroupLayout EmployeeMang_panelLayout = new javax.swing.GroupLayout(EmployeeMang_panel);
        EmployeeMang_panel.setLayout(EmployeeMang_panelLayout);
        EmployeeMang_panelLayout.setHorizontalGroup(
            EmployeeMang_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeMang_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EmployeeMang_panelLayout.setVerticalGroup(
            EmployeeMang_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeMang_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Payroll_panel.setBackground(new java.awt.Color(33, 33, 33));
        Payroll_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Payroll_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Payroll_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Payroll_panelMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salary (1).png"))); // NOI18N
        jLabel5.setText("Payroll");

        javax.swing.GroupLayout Payroll_panelLayout = new javax.swing.GroupLayout(Payroll_panel);
        Payroll_panel.setLayout(Payroll_panelLayout);
        Payroll_panelLayout.setHorizontalGroup(
            Payroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Payroll_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Payroll_panelLayout.setVerticalGroup(
            Payroll_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Payroll_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Leave_panel.setBackground(new java.awt.Color(33, 33, 33));
        Leave_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Leave_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Leave_panelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Leave_panelMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit (1).png"))); // NOI18N
        jLabel6.setText("Leave Request");

        javax.swing.GroupLayout Leave_panelLayout = new javax.swing.GroupLayout(Leave_panel);
        Leave_panel.setLayout(Leave_panelLayout);
        Leave_panelLayout.setHorizontalGroup(
            Leave_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Leave_panelLayout.setVerticalGroup(
            Leave_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Leave_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.setBackground(new java.awt.Color(33, 33, 33));
        jPanel12.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/motorcycle (1).png"))); // NOI18N
        jLabel1.setText("MOTORPH");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Profile_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EmployeeMang_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Payroll_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Leave_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Dashboard_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Profile_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmployeeMang_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Payroll_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Leave_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 202, 470);

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        logout_bttn.setBackground(new java.awt.Color(255, 51, 51));
        logout_bttn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout_bttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout (2).png"))); // NOI18N
        logout_bttn.setText("Logout");
        logout_bttn.setBorder(null);
        logout_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_bttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(434, Short.MAX_VALUE)
                .addComponent(logout_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(200, 0, 580, 60);

        Dashboard_Tab.setBackground(new java.awt.Color(255, 204, 102));

        jPanel4.setBackground(new java.awt.Color(204, 153, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/waving-hand (1).png"))); // NOI18N
        jLabel13.setText("  Welcome back, User");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(21, 21, 21))
        );

        list1.setBackground(new java.awt.Color(204, 153, 0));
        list1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("My Tasks :");

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Add Task");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setText("Announcements");

        list2.setBackground(new java.awt.Color(204, 153, 0));

        javax.swing.GroupLayout Dashboard_TabLayout = new javax.swing.GroupLayout(Dashboard_Tab);
        Dashboard_Tab.setLayout(Dashboard_TabLayout);
        Dashboard_TabLayout.setHorizontalGroup(
            Dashboard_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard_TabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dashboard_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Dashboard_TabLayout.createSequentialGroup()
                        .addGroup(Dashboard_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Dashboard_TabLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Dashboard_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Dashboard_TabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(list2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dashboard_TabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel30)
                                .addGap(111, 111, 111))))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Dashboard_TabLayout.setVerticalGroup(
            Dashboard_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dashboard_TabLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Dashboard_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton1)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Dashboard_TabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(list2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("tab1", Dashboard_Tab);

        Profile_tab.setBackground(new java.awt.Color(255, 204, 102));

        jPanel5.setBackground(new java.awt.Color(204, 153, 0));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (4) (2).png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Manuel Garcia III");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Birthdate: 10/11/1983");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Employee #: 1");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Phone #: 966-860-970");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setText("Regular");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jLabel15)))
                    .addComponent(jLabel14)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel25)
                        .addComponent(jLabel17)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(43, 43, 43))
        );

        jPanel6.setBackground(new java.awt.Color(204, 153, 0));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("SSS:");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Philhealth:");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("TIN:");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Pag-ibig:");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Address: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(34, 34, 34))
        );

        jPanel7.setBackground(new java.awt.Color(204, 153, 0));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Position:");

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setText("Immediate Supervisor:");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Basic Salary:");

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setText("Hourly Rate");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel29.setText("Gross semi-monthly rate:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Profile_tabLayout = new javax.swing.GroupLayout(Profile_tab);
        Profile_tab.setLayout(Profile_tabLayout);
        Profile_tabLayout.setHorizontalGroup(
            Profile_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_tabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(Profile_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Profile_tabLayout.setVerticalGroup(
            Profile_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_tabLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(Profile_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Profile_tabLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", Profile_tab);

        Empmanage_tab.setBackground(new java.awt.Color(255, 204, 102));

        employee_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee #", "Last Name", "First Name", "Address", "Birthdate", "Position"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employee_Table.setFocusable(false);
        employee_Table.setGridColor(new java.awt.Color(255, 255, 255));
        employee_Table.setShowGrid(true);
        employee_Table.getTableHeader().setReorderingAllowed(false);
        employee_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                employee_TableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(employee_Table);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("First Name");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Last Name");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Address");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Birthdate");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Position");

        add_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add (1).png"))); // NOI18N
        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        edit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit (1).png"))); // NOI18N
        edit_btn.setText("Edit");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete (1).png"))); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        delete_btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rubber (1).png"))); // NOI18N
        delete_btn1.setText("Clear");
        delete_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Empmanage_tabLayout = new javax.swing.GroupLayout(Empmanage_tab);
        Empmanage_tab.setLayout(Empmanage_tabLayout);
        Empmanage_tabLayout.setHorizontalGroup(
            Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Empmanage_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Empmanage_tabLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Empmanage_tabLayout.createSequentialGroup()
                                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(delete_btn))
                            .addGroup(Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(Empmanage_tabLayout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(firstname_txtfield))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Empmanage_tabLayout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lastname_txtfield))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Empmanage_tabLayout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addresstxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Empmanage_tabLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Empmanage_tabLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(birthdate_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Empmanage_tabLayout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(position_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(Empmanage_tabLayout.createSequentialGroup()
                                .addComponent(delete_btn1)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        Empmanage_tabLayout.setVerticalGroup(
            Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Empmanage_tabLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birthdate_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(position_txtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addresstxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(Empmanage_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("tab3", Empmanage_tab);

        jButton4.setText("Tab4");

        javax.swing.GroupLayout Payroll_tabLayout = new javax.swing.GroupLayout(Payroll_tab);
        Payroll_tab.setLayout(Payroll_tabLayout);
        Payroll_tabLayout.setHorizontalGroup(
            Payroll_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Payroll_tabLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jButton4)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        Payroll_tabLayout.setVerticalGroup(
            Payroll_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Payroll_tabLayout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(150, 150, 150))
        );

        jTabbedPane1.addTab("tab4", Payroll_tab);

        jButton5.setText("Tab5");

        javax.swing.GroupLayout Leave_tabLayout = new javax.swing.GroupLayout(Leave_tab);
        Leave_tab.setLayout(Leave_tabLayout);
        Leave_tabLayout.setHorizontalGroup(
            Leave_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave_tabLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jButton5)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        Leave_tabLayout.setVerticalGroup(
            Leave_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Leave_tabLayout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(133, 133, 133))
        );

        jTabbedPane1.addTab("tab5", Leave_tab);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(204, -40, 580, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        
    public void resetData(){
        String query = null;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection(SUrl,SUser,SPass); 
                Statement st = con.createStatement();
                
                query = "SELECT * FROM users";
                ResultSet rs = st.executeQuery(query);
                
                while(rs.next()){
                    String id = String.valueOf(rs.getInt("id"));
                    String Lastname = rs.getString("Last Name");
                    String Firstname = rs.getString("First Name");
                    String Address = rs.getString("Address");
                    String Birthdate = rs.getString("Birthdate");
                    String Position = rs.getString("Position");
                    
                    String tbdata [] = {id,Lastname,Firstname,Address,Birthdate,Position};
                    DefaultTableModel tablemodel = (DefaultTableModel)employee_Table.getModel();
                    
                    tablemodel.addRow(tbdata);
                    
                    
                }
            
            
            
            
            
        }catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }
    private void EmployeeMang_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMang_panelMousePressed
        Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(defaultColor);
        EmployeeMang_panel.setBackground(clickedColor);
        Payroll_panel.setBackground(defaultColor);
        Leave_panel.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_EmployeeMang_panelMousePressed

    private void Payroll_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Payroll_panelMousePressed
        Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(defaultColor);
        EmployeeMang_panel.setBackground(defaultColor);
        Payroll_panel.setBackground(clickedColor);
        Leave_panel.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_Payroll_panelMousePressed

    private void Leave_panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leave_panelMousePressed
         Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(defaultColor);
        EmployeeMang_panel.setBackground(defaultColor);
        Payroll_panel.setBackground(defaultColor);
        Leave_panel.setBackground(clickedColor);
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_Leave_panelMousePressed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
        String query = null;
        
        int selected = employee_Table.getSelectedRow();
         if (selected<0){
                showMessageDialog(null,"Please select an employee to remove","Error",JOptionPane.ERROR_MESSAGE);
            }
         else{
        int response = JOptionPane.showConfirmDialog(null,"Are you sure you want to delete?","Confirm",JOptionPane.YES_NO_OPTION);
        int id = Integer.parseInt(employee_Table.getValueAt(employee_Table.getSelectedRow(),0).toString());

             if(response == JOptionPane.YES_OPTION){
        try{    
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = con.createStatement();
            query = ("DELETE FROM users where id="+id);
            st.execute(query);
            
            DefaultTableModel tablemodel = (DefaultTableModel)employee_Table.getModel();
            tablemodel.setRowCount(0);   
            resetData();
            
            firstname_txtfield.setText("");
            lastname_txtfield.setText("");
            addresstxtfield.setText("");
            birthdate_txtfield.setText("");
            position_txtfield.setText("");
            
            showMessageDialog(null,"Deleted Successfully","Message",JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch(Exception e){
            System.out.println("Error: "+ e.getMessage());
        }
             }else if(response == JOptionPane.NO_OPTION){
            firstname_txtfield.setText("");
            lastname_txtfield.setText("");
            addresstxtfield.setText("");
            birthdate_txtfield.setText("");
            position_txtfield.setText(""); 
             }
             
        
         }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        String query, lastname,firstname,address,birthdate,Position;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = con.createStatement();
            if(firstname_txtfield.getText().isBlank()||lastname_txtfield.getText().isBlank()
                    ||addresstxtfield.getText().isBlank()||birthdate_txtfield.getText().isBlank()
                    ||position_txtfield.getText().isBlank()){
                showMessageDialog(null,"Please fillup all information","Invalid",JOptionPane.ERROR_MESSAGE);
            }
            else{
            firstname = firstname_txtfield.getText();
            lastname= lastname_txtfield.getText();
            address= addresstxtfield.getText();
            birthdate= birthdate_txtfield.getText();
            Position = position_txtfield.getText();
                                                                     
            query = "INSERT INTO users(`Last Name`, `First Name`, Address, Birthdate, Position) " + "VALUES('"+ lastname +"', '"+ firstname +"', '"+ address +"', '"+ birthdate +"', '"+ Position +"')";
                                    
            st.execute(query);
            
            DefaultTableModel tablemodel = (DefaultTableModel)employee_Table.getModel();
            tablemodel.setRowCount(0);            
          
            resetData();
            firstname_txtfield.setText("");
            lastname_txtfield.setText("");
            addresstxtfield.setText("");
            birthdate_txtfield.setText("");
            position_txtfield.setText("");
            
            showMessageDialog(null,"Addedd Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void logout_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_bttnActionPerformed
        dispose();
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_logout_bttnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        String query, lastname,firstname,address,birthdate,Position;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
        int selected = employee_Table.getSelectedRow();
        if(selected<0){
            showMessageDialog(null,"Please select an employee to update","Error",JOptionPane.ERROR_MESSAGE);
        }
        else{
        try{
            int confirm = JOptionPane.showConfirmDialog(null,"Are you sure you want to update?","Confirm",JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
            
            int id = Integer.parseInt(employee_Table.getValueAt(employee_Table.getSelectedRow(),0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = con.createStatement();
            
            firstname = firstname_txtfield.getText();
            lastname= lastname_txtfield.getText();
            address= addresstxtfield.getText();
            birthdate= birthdate_txtfield.getText();
            Position = position_txtfield.getText();
            
            query = ("UPDATE users set `First Name`='"+firstname+"',`Last Name`='"+lastname+"',Address = '"+address+"',Birthdate = '"+birthdate+"',Position ='"+Position+"' where id="+id);
            st.executeUpdate(query);
                         
            DefaultTableModel tablemodel = (DefaultTableModel)employee_Table.getModel();
            tablemodel.setRowCount(0);
            
            resetData();
            
            firstname_txtfield.setText("");
            lastname_txtfield.setText("");
            addresstxtfield.setText("");
            birthdate_txtfield.setText("");
            position_txtfield.setText("");
            showMessageDialog(null,"Update Successful!","Message",JOptionPane.INFORMATION_MESSAGE);
            
            }

            
            
        }catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
        }
    }//GEN-LAST:event_edit_btnActionPerformed

    private void delete_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btn1ActionPerformed
        firstname_txtfield.setText("");
            lastname_txtfield.setText("");
            addresstxtfield.setText("");
            birthdate_txtfield.setText("");
            position_txtfield.setText("");
            
    }//GEN-LAST:event_delete_btn1ActionPerformed

    private void EmployeeMang_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMang_panelMouseEntered
        
    }//GEN-LAST:event_EmployeeMang_panelMouseEntered

    private void EmployeeMang_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeMang_panelMouseExited
      
    }//GEN-LAST:event_EmployeeMang_panelMouseExited

    private void Payroll_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Payroll_panelMouseEntered
    
    }//GEN-LAST:event_Payroll_panelMouseEntered

    private void Payroll_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Payroll_panelMouseExited
    
    }//GEN-LAST:event_Payroll_panelMouseExited

    private void Leave_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leave_panelMouseEntered
      
    }//GEN-LAST:event_Leave_panelMouseEntered

    private void Leave_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leave_panelMouseExited
      
    }//GEN-LAST:event_Leave_panelMouseExited

    private void Dashboard_PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard_PanelMousePressed
         Dashboard_Panel.setBackground(clickedColor);
        Profile_Panel.setBackground(defaultColor);
        EmployeeMang_panel.setBackground(defaultColor);
        Payroll_panel.setBackground(defaultColor);
        Leave_panel.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Dashboard_PanelMousePressed

    private void Profile_PanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Profile_PanelMousePressed
        Dashboard_Panel.setBackground(defaultColor);
        Profile_Panel.setBackground(clickedColor);
        EmployeeMang_panel.setBackground(defaultColor);
        Payroll_panel.setBackground(defaultColor);
        Leave_panel.setBackground(defaultColor);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_Profile_PanelMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String task = JOptionPane.showInputDialog("Enter task");
        list1.add(task);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void employee_TableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employee_TableMousePressed
        String query = null;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
 
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = con.createStatement();
            int id = Integer.parseInt(employee_Table.getValueAt(employee_Table.getSelectedRow(),0).toString());
            query = ("SELECT * from users where id="+id);
            ResultSet rs = st.executeQuery(query);
            
            
            while(rs.next()){
                firstname_txtfield.setText(rs.getString("First Name"));
                lastname_txtfield.setText(rs.getString("Last Name"));
                addresstxtfield.setText(rs.getString("Address"));
                birthdate_txtfield.setText(rs.getString("Birthdate"));
                position_txtfield.setText(rs.getString("Position"));
            }
            
        }catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_employee_TableMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard_Panel;
    private javax.swing.JPanel Dashboard_Tab;
    private javax.swing.JPanel EmployeeMang_panel;
    private javax.swing.JPanel Empmanage_tab;
    private javax.swing.JPanel Leave_panel;
    private javax.swing.JPanel Leave_tab;
    private javax.swing.JPanel Payroll_panel;
    private javax.swing.JPanel Payroll_tab;
    private javax.swing.JPanel Profile_Panel;
    private javax.swing.JPanel Profile_tab;
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField addresstxtfield;
    private javax.swing.JTextField birthdate_txtfield;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton delete_btn1;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTable employee_Table;
    private javax.swing.JTextField firstname_txtfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastname_txtfield;
    private java.awt.List list1;
    private java.awt.List list2;
    private javax.swing.JButton logout_bttn;
    private javax.swing.JTextField position_txtfield;
    // End of variables declaration//GEN-END:variables
}
