/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payrollsystem;


import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;

/**
 *
 * @author keith
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public LoginPage() {
        initComponents();
    }
class PayrollSystem extends JPanel{
        
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            Color Color1 = new Color(1,30,30);
            Color Color2 = new Color(0,102,102);
            GradientPaint gp = new GradientPaint(0,0,Color1,180,height,Color2);
            g2d.setPaint(gp);
            g2d.fillRect(0,0,width,height);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MotorPhLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        PassworLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        MotorPhLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        MotorPhLabel.setBackground(new java.awt.Color(255, 204, 51));
        MotorPhLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        MotorPhLabel.setForeground(new java.awt.Color(255, 255, 255));
        MotorPhLabel.setText("MotorPH Payroll");
        jPanel1.add(MotorPhLabel);
        MotorPhLabel.setBounds(37, 13, 290, 39);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile (1).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 180, 31, 50);

        UsernameTextField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameTextField);
        UsernameTextField.setBounds(29, 183, 290, 43);

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsernameLabel.setText("Username");
        jPanel1.add(UsernameLabel);
        UsernameLabel.setBounds(30, 150, 62, 20);

        PassworLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PassworLabel.setForeground(new java.awt.Color(255, 255, 255));
        PassworLabel.setText("Password");
        jPanel1.add(PassworLabel);
        PassworLabel.setBounds(30, 240, 58, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unlock (1).png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 260, 30, 70);

        PasswordField.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jPanel1.add(PasswordField);
        PasswordField.setBounds(29, 270, 290, 44);

        LoginButton.setBackground(new java.awt.Color(0, 153, 153));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.setBorder(null);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginButton.setFocusable(false);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LoginButton);
        LoginButton.setBounds(29, 368, 290, 40);

        MotorPhLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        MotorPhLabel1.setForeground(new java.awt.Color(255, 255, 255));
        MotorPhLabel1.setText("System");
        jPanel1.add(MotorPhLabel1);
        MotorPhLabel1.setBounds(111, 58, 121, 39);

        jCheckBox1.setBackground(new java.awt.Color(33, 33, 33));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(30, 330, 123, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 480);

        jPanel2.setBackground(new java.awt.Color(0, 27, 27));
        jPanel2.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(440, 30, 260, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lol.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 0, 460, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MYSQL://localhost:3306/employee_database";
        SUser = "root";
        SPass = "";
        String query = null;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl,SUser,SPass);
            Statement st = con.createStatement();
            
            String username = UsernameTextField.getText();
            String password = String.valueOf(PasswordField.getPassword());
            
            query = "SELECT * FROM users WHERE BINARY Username = '"+username+"' and Password = '"+password+"' ";
            
            ResultSet rs = st.executeQuery(query);
            
            String firstname = null;
            String lastname = null;
            String role = null;
            String id = null;
            String bday = null;
            String phoneNum = null;
            String SSS = null;
            String Philhealth = null;
            String TIN = null;
            String Pagibig = null;
            String position = null;
            String salary = null;
            String grossrate = null;
            String hourlyrate = null;
            String status = null;
            
            

           
            if(username.isBlank() || password.isBlank()|| username.isBlank() && password.isBlank()){
                showMessageDialog(null,"Please fillup all information","Error",JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(rs.next()){
                    role = rs.getString("Role");
                    id = String.valueOf(rs.getInt("id"));
                    firstname = rs.getString("First Name");
                    lastname = rs.getString("Last Name");
                    bday = rs.getString("Birthdate");
                    phoneNum = rs.getString("Phone_number");
                    SSS = rs.getString("SSS");
                    Philhealth = rs.getString("Philhealth");
                    TIN = rs.getString("TIN");
                    Pagibig = rs.getString("Pagibig");
                    position = rs.getString("Position");
                    salary = rs.getString("Basic_salary");
                    grossrate = rs.getString("Gross_semi_monthly_rate");
                    hourlyrate = rs.getString("Hourly_rate");
                    status = rs.getString("Status");
                    
                    
                if(role.equals("Admin")){
                    dispose();
                    DashBoardPageAdmin adminpage = new DashBoardPageAdmin(firstname,lastname,id,bday,
                    phoneNum,SSS,Philhealth,TIN,Pagibig,position,salary,grossrate,hourlyrate,status);
                    adminpage.setVisible(true);
                            

                    
                }else{
                    dispose();
                    DashBoardPageEmployee employeepage = new DashBoardPageEmployee(firstname,lastname,id,bday,
                    phoneNum,SSS,Philhealth,TIN,Pagibig,position,salary,grossrate,hourlyrate,status);
                    employeepage.setVisible(true);
                }

                }else{
                    showMessageDialog(null,"Username or password is incorrect","Error",JOptionPane.ERROR_MESSAGE);
                    UsernameTextField.setText("");
                    PasswordField.setText("");        
                }
            }
            con.close();
            st.close();
            rs.close();
            
            
            
            
        }catch(Exception e){
            System.out.println("Error: "+ e.getMessage());
        }

        
        
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            PasswordField.setEchoChar((char)0);
        }else{
            PasswordField.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel MotorPhLabel;
    private javax.swing.JLabel MotorPhLabel1;
    private javax.swing.JLabel PassworLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
